CREATE DATABASE  IF NOT EXISTS `USUARIS`;
USE USUARIS;

-- Exemple opcional
CREATE TABLE IF NOT EXISTS usuari (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('admin', 'user') DEFAULT 'user'
);